---
- name: Configure web server
  hosts: web
  become: True
  vars_files:
    - variables.yml
  tasks:
    - name: manage packages
      yum: >
        name={{ item.name }}
        state={{ item.state }}
      with_items:
        "{{ packages }}"
    - name: add admin user
      user: >
        name={{ admin_user }}
        state=present

